# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 0.7
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --color=yes -e 'using InteractiveUtils; versioninfo(); import Pkg; Pkg.clone(pwd()); Pkg.build("IndirectArrays")'
  - julia --color=yes --check-bounds=yes -e 'import Pkg; Pkg.test("IndirectArrays"; coverage=true)'
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("IndirectArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
