name = "IndirectArrays"
uuid = "9b13fd28-a010-5f03-acff-a1bbcff69959"
version = "1.0.0"

[deps]

[compat]
FixedPointNumbers = "0.5, 0.6, 0.7"
julia = "1"

[extras]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MappedArrays", "Colors", "FixedPointNumbers", "OrderedCollections"]
